data_ingestion:
  bucket_name: "mlops-2-a"
  bucket_file_names:
    - "anime.csv"
    - "anime_with_synopsis.csv"
    - "animelist.csv"


model_trainer:
  embedding_size : 128
  loss : binary_crossentropy
  optimizer : Adam
  metrics : ["mae","mse"]
